name: Build for check

on:
  pull_request:
    paths:
      - "src/**"
      - "package.json"
      - "yarn.lock"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      MAC_OS_VERSION: macOS-10.15
      WIN_OS_VERSION: windows-2016

    strategy:
      matrix:
        # この中でenvにアクセスできないので直書き
        os: [macOS-10.15, windows-2016]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: v16.x
      - name: yarn install
        run: |
          yarn install
          yarn postinstall

      - name: Build for macOS
        if: matrix.os == env.MAC_OS_VERSION
        run: yarn electron:build --publish never --mac
        env:
          USE_HARD_LINKS: false

      - name: Build for Windows
        if: matrix.os == env.WIN_OS_VERSION
        run: yarn electron:build --publish never --win
        env:
          USE_HARD_LINKS: false
