name: Build for check

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # この中でenvにアクセスできないので直書き
        os: [macOS-10.15, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: v16.x
      - name: yarn install
        run: |
          yarn install
          yarn postinstall

      - name: Build for macOS
        if: startsWith(matrix.os, 'mac')
        run: yarn electron:build --publish never --mac
        env:
          USE_HARD_LINKS: false

      - name: Build for Windows
        if: startsWith(matrix.os, 'win')
        run: yarn electron:build --publish never --win
        env:
          USE_HARD_LINKS: false
