name: Release

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # この中でenvにアクセスできないので直書き
        os: [macOS-11, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set release version
        shell: bash
        run: echo "RELEASE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: v16.x
      - name: yarn install
        run: |
          yarn install
          yarn postinstall

      - name: Create GitHub Release(Mac)
        if: startsWith(matrix.os, 'mac')
        uses: ./.github/actions/create-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_version: ${{ env.RELEASE_VERSION }}
          os_name: "mac"
          file_path: "dist_electron/sound-of-cthulhu*.dmg"

      - name: Create GitHub Release(Win)
        if: startsWith(matrix.os, 'win')
        uses: ./.github/actions/create-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_version: ${{ env.RELEASE_VERSION }}
          os_name: "win"
          file_path: "dist_electron/sound-of-cthulhu*.exe"
