name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: v16.x

      - name: install dependencies
        run: yarn install

      - name: unit test
        run: yarn test:unit
      - name: lint
        run: yarn ci:lint
